#!/usr/bin/env python3
"""
02b_audit_vs_skillmd.py — Section 2 follow-up: is the ~9.7% of the population
without audit records the SAME set as the ~36.1% without a retrievable SKILL.md?

Builds a 2x2 contingency table of has_any_audit x has_skill_md over the 5,235
population skills, prints counts, row percentages, and the conditional
probabilities both ways, and writes a one-paragraph descriptive note to
reports/02b_audit_vs_skillmd.md. No figure; the numbers are enough.

Self-contained: reads ONLY from analysis/data/population.parquet. Descriptive
only — no interpretation.

Run from anywhere:
    python3 scripts/02b_audit_vs_skillmd.py
"""

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _style as st  # noqa: E402

DATA_DIR = st.DATA_DIR
REPORTS_DIR = st._ANALYSIS_DIR / "reports"
AUDIT_COLS = ["snyk_status", "socket_status", "agent_trust_hub_status"]


def main():
    pop = pd.read_parquet(DATA_DIR / "population.parquet")
    n = len(pop)

    pop["has_any_audit"] = pop[AUDIT_COLS].notna().any(axis=1)
    pop["has_skill_md"] = pop["has_skill_md"].eq("Y")

    # 2x2 contingency: rows = has_any_audit, cols = has_skill_md
    ct = pd.crosstab(pop["has_any_audit"], pop["has_skill_md"])
    ct = ct.reindex(index=[True, False], columns=[True, False])

    a = int(ct.loc[True, True])    # audit  & md
    b = int(ct.loc[True, False])   # audit  & no md
    c = int(ct.loc[False, True])   # no audit & md
    d = int(ct.loc[False, False])  # no audit & no md

    n_audit = a + b
    n_noaudit = c + d
    n_md = a + c
    n_nomd = b + d

    # Conditional probabilities (both directions).
    p_md_given_noaudit = c / n_noaudit
    p_md_given_audit = a / n_audit
    p_audit_given_md = a / n_md
    p_audit_given_nomd = b / n_nomd

    # ---- console ----
    print("=" * 64)
    print("PART 0 — has_any_audit x has_skill_md  (population, n=%d)" % n)
    print("=" * 64)
    print("\nAbsolute counts:")
    print(f"  {'':14s}{'md=Y':>10s}{'md=N':>10s}{'total':>10s}")
    print(f"  {'audit=Y':14s}{a:>10d}{b:>10d}{n_audit:>10d}")
    print(f"  {'audit=N':14s}{c:>10d}{d:>10d}{n_noaudit:>10d}")
    print(f"  {'total':14s}{n_md:>10d}{n_nomd:>10d}{n:>10d}")

    print("\nRow percentages (within each audit row):")
    print(f"  audit=Y : md=Y {a / n_audit * 100:5.1f}%   md=N {b / n_audit * 100:5.1f}%")
    print(f"  audit=N : md=Y {c / n_noaudit * 100:5.1f}%   md=N {d / n_noaudit * 100:5.1f}%")

    print("\nConditional probabilities:")
    print(f"  P(has_skill_md | no audit)  = {p_md_given_noaudit * 100:5.1f}%  ({c}/{n_noaudit})")
    print(f"  P(has_skill_md | has audit) = {p_md_given_audit * 100:5.1f}%  ({a}/{n_audit})")
    print(f"  P(has audit | has_skill_md) = {p_audit_given_md * 100:5.1f}%  ({a}/{n_md})")
    print(f"  P(has audit | no skill_md)  = {p_audit_given_nomd * 100:5.1f}%  ({b}/{n_nomd})")

    # ---- report ----
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    note = f"""# Section 2 follow-up — audit records vs. `SKILL.md` retrievability

*Phase E. Generated by `scripts/02b_audit_vs_skillmd.py`, reading only from
`data/population.parquet`. Descriptive only.*

This note checks whether the ~9.7% of the population with no audit record from
any of the three auditors is the **same** set as the ~36.1% with no retrievable
`SKILL.md`. Both gaps were flagged in Section 2 as plausibly tied to
non-standard repository layouts; this cross-tab tests that.

## 2x2 contingency table (n = {n:,})

| | `SKILL.md` = Y | `SKILL.md` = N | total |
|---|---|---|---|
| **any audit = Y** | {a:,} | {b:,} | {n_audit:,} |
| **any audit = N** | {c:,} | {d:,} | {n_noaudit:,} |
| **total** | {n_md:,} | {n_nomd:,} | {n:,} |

Row percentages: among skills **with** an audit record, {a / n_audit * 100:.1f}%
have a retrievable `SKILL.md` and {b / n_audit * 100:.1f}% do not; among skills
**without** any audit record, {c / n_noaudit * 100:.1f}% have a retrievable
`SKILL.md` and {d / n_noaudit * 100:.1f}% do not.

## Conditional probabilities

- P(has `SKILL.md` | no audit) = {p_md_given_noaudit * 100:.1f}% ({c:,}/{n_noaudit:,})
- P(has `SKILL.md` | has audit) = {p_md_given_audit * 100:.1f}% ({a:,}/{n_audit:,})
- P(has audit | has `SKILL.md`) = {p_audit_given_md * 100:.1f}% ({a:,}/{n_md:,})
- P(has audit | no `SKILL.md`) = {p_audit_given_nomd * 100:.1f}% ({b:,}/{n_nomd:,})

## Pattern

The two gaps are not the same set. Of the {n_noaudit:,} skills with no audit
record, {c:,} ({p_md_given_noaudit * 100:.1f}%) still have a retrievable
`SKILL.md`, and only {d:,} fall in both gaps at once. The `SKILL.md`
retrievability rate is {p_md_given_noaudit * 100:.1f}% among skills with no
audit versus {p_md_given_audit * 100:.1f}% among skills with an audit — a
difference of {(p_md_given_audit - p_md_given_noaudit) * 100:.1f} percentage
points. Read the other way, the any-audit rate is {p_audit_given_nomd * 100:.1f}%
among skills with no retrievable `SKILL.md` versus {p_audit_given_md * 100:.1f}%
among skills with one, a difference of
{(p_audit_given_md - p_audit_given_nomd) * 100:.1f} percentage points. Knowing
that a skill lacks an audit record barely shifts its `SKILL.md` retrievability
rate, and vice versa.
"""
    out = REPORTS_DIR / "02b_audit_vs_skillmd.md"
    out.write_text(note)
    print(f"\nWrote {out}")


if __name__ == "__main__":
    main()
